// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.get('FCM_ANDROID_API_KEY'),
        appId: dotenv.get('FCM_ANDROID_APP_ID'),
        messagingSenderId: dotenv.get('FCM_MESSAGING_SENDER_ID'),
        projectId: dotenv.get('FCM_PROJECT_ID'),
        databaseURL: dotenv.get('FCM_DATABASE_URL'),
        storageBucket: dotenv.get('FCM_STORAGE_BUCKET'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.get('FCM_API_KEY'),
        appId: dotenv.get('FCM_IOS_APP_ID'),
        messagingSenderId: dotenv.get('FCM_MESSAGING_SENDER_ID'),
        projectId: dotenv.get('FCM_PROJECT_ID'),
        databaseURL: dotenv.get('FCM_DATABASE_URL'),
        storageBucket: dotenv.get('FCM_STORAGE_BUCKET'),
        iosBundleId: dotenv.get('FCM_IOS_BUNDLE_ID'),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.get('FCM_API_KEY'),
        appId: dotenv.get('FCM_IOS_APP_ID'),
        messagingSenderId: dotenv.get('FCM_MESSAGING_SENDER_ID'),
        projectId: dotenv.get('FCM_PROJECT_ID'),
        databaseURL: dotenv.get('FCM_DATABASE_URL'),
        storageBucket: dotenv.get('FCM_STORAGE_BUCKET'),
        iosBundleId: dotenv.get('FCM_IOS_BUNDLE_ID'),
      );
}
