icon: linux/assets/logo.png
summary: Keychat is the super app for Bitcoiners.Autonomous IDs, Bitcoin ecash wallet, secure chat, and rich mini apps — all in Keychat. Autonomy. Security. Richness.
group: Application/Chat
vendor: Keychat
packager: Keychat
packagerEmail: btc001@tuta.io
license: GPLv3
url: https://github.com/keychat-io/keychat-app

display_name: Keychat

keywords:
  - Keychat
  - Nostr
  - Ecash
  - cashu

generic_name: Keychat

categories:
  - Chat

startup_notify: true