display_name: Keychat
package_name: com.keychat.io

maintainer:
  name: Keychat
  email: btc001@tuta.io

priority: optional

section: x11

installed_size: 15700

dependencies:
  - libsecret-1-dev
  - libjsoncpp-dev

essential: false

icon: linux/assets/logo.png

postuninstall_scripts:
  - echo "Sorry to see you go."
postinstall_scripts:
  - echo "Installed! Keychat is the super app for Bitcoiners."

keywords:
  - Keychat
  - Nostr
  - Ecash
  - cashu

generic_name: Keychat

categories:
  - Chat

startup_notify: true