display_name: Keychat
publisher: KEYME PTE. LTD.
publisher_display_name: KEYME PTE. LTD.
identity_name: com.keychat.io
logo_path: assets/images/logo.png
capabilities: internetClient, webcam, documentsLibrary
languages: en-us
install_certificate: "false"
sign_msix: "false"
certificate_path: ""
certificate_password: ""
# fastforge package --platform windows --targets msix --skip-clean true
