app_id: e9834b7f-d83c-4129-b42b-99c39cbe3384
publisher: Keyme
publisher_url: https://github.com/keychat-io/keychat-app
display_name: Keychat
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
install_dir_name: "C:\\Program Files\\Keychat"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
